# Generated by Django 4.0.6 on 2022-08-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'verbose_name_plural': 'salaries'},
        ),
    ]
